FROM node:13.1-alpine as react-build
WORKDIR /usr/src/app
COPY . ./
RUN yarn && yarn build

FROM nginx:alpine
COPY --from=react-build usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
